
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iri_s
 */
public class UKTLogin extends javax.swing.JFrame {

    /**
     * Creates new form UKTLogin
     */
    public UKTLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblheaderlogin = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        errorMsgLogin = new javax.swing.JLabel();
        inputusername = new javax.swing.JTextField();
        inputpassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btnlogincancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UKT Login");
        setResizable(false);

        lblheaderlogin.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblheaderlogin.setText("UKT LOGIN");

        lblusername.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblusername.setText("Username");

        lblpassword.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblpassword.setText("Password");

        errorMsgLogin.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        errorMsgLogin.setForeground(new java.awt.Color(255, 51, 51));

        inputusername.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        inputpassword.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        btnlogin.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnlogin.setText("Add");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnlogincancel.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnlogincancel.setText("Cancel");
        btnlogincancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogincancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(errorMsgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnlogin))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputusername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnlogincancel))))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblheaderlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblheaderlogin)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(inputusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(errorMsgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlogin)
                    .addComponent(btnlogincancel))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
              PreparedStatement psstatement;
           ResultSet getresults;
           String username = inputusername.getText();
           String password = String.valueOf(inputpassword.getPassword());
          
           if(username.length()<=0 || password.length()<=0){
           errorMsgLogin.setText("Please enter username and password to login!");
           errorMsgLogin.setVisible(true);
           } else{
           errorMsgLogin.setVisible(false);
           
           String sql = "SELECT `username`, `password` FROM `user` WHERE `username` =? AND `password` =?";
           
            try{  
           psstatement= Mysql.getConnection().prepareStatement(sql); 
           
           psstatement.setString(1, username);
           psstatement.setString(2, password);
           getresults = psstatement.executeQuery();
if(getresults.next()){
                 
       
          new JavaGUIUKT().setVisible(true);
          this.dispose();
}
else
{
    JOptionPane.showMessageDialog(null, "Invalid login credentials! ");
}
            }
        catch(Exception except){
                    System.out.println("Error in login attempt");
        }
        inputusername.setText("");
        inputpassword.setText("");
        inputusername.requestFocus();
        }
    }//GEN-LAST:event_btnloginActionPerformed
                                                                                
    private void btnlogincancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogincancelActionPerformed
       inputusername.setText("");
       inputpassword.setText("");
       errorMsgLogin.setVisible(false);
       inputusername.requestFocus();
    }//GEN-LAST:event_btnlogincancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UKTLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UKTLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UKTLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UKTLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UKTLogin().setVisible(true);
                  
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogincancel;
    private javax.swing.JLabel errorMsgLogin;
    private javax.swing.JPasswordField inputpassword;
    private javax.swing.JTextField inputusername;
    private javax.swing.JLabel lblheaderlogin;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables
}
